INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('1', 'Bandarawela', '0', 'R01', '1');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('2', 'Bogahamaditta', '0', 'R02', '1');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('3', 'Haldamulla', '0', 'R03', '1');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('4', 'Hali Ela', '0', 'R04', '1');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('5', 'Palgahatanna', '0', 'R05', '1');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('6', 'Spring Vally', '0', 'R06', '1');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('7', 'Uva Wellassa', '0', 'R07', '1');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('8', 'Wewegama', '0', 'R08', '1');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('9', 'Bogawanthalawa', '0', 'R09', '24');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('10', 'Daraoya', '0', 'R10', '24');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('11', 'Kandapola', '0', 'R11', '24');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('12', 'Kotagala', '0', 'R12', '24');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('13', 'Kotmale', '0', 'R13', '24');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('14', 'Maldeniya', '0', 'R14', '24');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('15', 'Nanu Oya', '0', 'R15', '24');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('16', 'Nildandahinna', '0', 'R16', '24');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('17', 'Dolosbage', '0', 'R17', '16');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('18', 'Galaha', '0', 'R18', '16');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('19', 'Kadugannawa', '0', 'R19', '16');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('20', 'Kuruduwatta', '0', 'R20', '16');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('21', 'M. Mahanuwara', '0', 'R21', '16');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('22', 'Pussellawa', '0', 'R22', '16');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('23', 'Ududumbara', '0', 'R23', '16');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('24', 'Alkaduwa', '0', 'R24', '16');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('25', 'Gammaduwa', '0', 'R25', '16');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('26', 'Riverstan', '0', 'R26', '16');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('27', 'Aranayake', '0', 'R27', '16');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('28', 'Dedigama', '0', 'R28', '16');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('29', 'Dehiovita', '0', 'R29', '16');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('30', 'Deraniyagala', '0', 'R30', '16');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('31', 'Gatiyamulla', '0', 'R31', '16');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('32', 'Kegalu MV', '0', 'R32', '16');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('33', 'Kitulgala', '0', 'R33', '16');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('34', 'Ridigama', '0', 'R34', '18');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('35', 'Walpolakanda', '0', 'R35', '18');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('36', 'Pelmadulla', '0', 'R36', '27');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('37', 'Kahawatta', '0', 'R37', '27');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('38', 'Nivithigala', '0', 'R38', '27');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('39', 'Elapatha', '0', 'R39', '27');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('40', 'Kalawana', '0', 'R40', '27');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('41', 'Ingiriya', '0', 'R41', '15');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('42', 'Bulathsinhala', '0', 'R42', '15');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('43', 'Baduraliya', '0', 'R43', '15');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('44', 'Agalawaththa', '0', 'R44', '15');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('45', 'Walallavita MV', '0', 'R45', '15');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('46', 'Yakkalamulla', '0', 'R46', '9');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('47', 'Baddegama', '0', 'R47', '9');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('48', 'Nagoda', '0', 'R48', '9');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('49', 'Elpitiya', '0', 'R49', '9');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('50', 'Neluwa', '0', 'R50', '9');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('51', 'Kalubowitiyana', '0', 'R51', '21');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('52', 'Morawaka', '0', 'R52', '21');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('53', 'Pallegama', '0', 'R53', '21');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('54', 'Bengamuwa', '0', 'R54', '21');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('55', 'Urubokka', '0', 'R55', '21');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('56', 'Madakanda', '0', 'R56', '11');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('57', 'Walasmulla', '0', 'R57', '11');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('58', 'Warapitiya', '0', 'R58', '11');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('59', 'Dewathura Pri.', '0', 'R59', '30');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('60', 'Yalkumbura', '0', 'R60', '30');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('61', 'Wellawaya', '0', 'R61', '30');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('62', 'Eheliyagoda', '0', 'R62', '27');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('63', 'Endane', '0', 'R63', '27');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('64', 'Erathna MV', '0', 'R64', '27');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('65', 'Kaltota', '0', 'R65', '27');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('66', 'Namunuthenna', '0', 'R66', '27');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('67', 'Omalpe', '0', 'R67', '27');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('68', 'Pinnawala', '0', 'R68', '27');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('69', 'Rambuka MV', '0', 'R69', '27');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('70', 'Ratnapura', '0', 'R70', '27');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('71', 'Suriyakanda', '0', 'R71', '27');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('72', 'Ulinduwawa', '0', 'R72', '27');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('73', 'Waleboda', '0', 'R73', '27');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('74', 'Weligepola', '0', 'R74', '27');
INSERT INTO `nbrodb`.`raingauge` (`raingauge_id`, `raingauge`, `version_id`, `raingauge_code`, `district_id`) VALUES ('75', 'R75 Wewelwaththa', '0', 'R75', '27');
